const level1 = new Level(
    [
        new Enemies(),
        new Enemies(),
        new Enemies(),
        new Endboss(),
        new Coin(400, 350),
        new Coin(800, 300),
        new Coin(1200, 250),
        new Coin(1600, 500),
        new Coin(2000, 250)
    ],
    [
        new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', 0),    
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D1.png', 0),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', 0),
        new BackgroundObject('img/3. Background/Layers/1. Light/1.png', 0),
        new BackgroundObject('img/3. Background/Legacy/Layers/2. Floor/D1.png', 0),
        new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', 720),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D2.png', 720),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', 720),
        new BackgroundObject('img/3. Background/Layers/1. Light/2.png', 720),
        new BackgroundObject('img/3. Background/Legacy/Layers/2. Floor/D2.png', 720),
        new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/1. Light/1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Legacy/Layers/2. Floor/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Layers/1. Light/2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Legacy/Layers/2. Floor/D2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', 720 * 4),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D1.png', 720 * 4),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', 720 * 4),
        new BackgroundObject('img/3. Background/Layers/1. Light/1.png', 720 * 4),
        new BackgroundObject('img/3. Background/Legacy/Layers/2. Floor/D1.png', 720 * 4)
    ]
);